version: '3.3'

services:
#  nginx:
#    image: nginx:latest
#    ports:
#      - "8000:8000"
#    volumes:
#      - .config/nginx:/etc/nginx/conf.d
#    depends_on:
#      - web
  db:
    image: postgres:latest
    container_name: soccer_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build: .
    container_name: soccer_api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    entrypoint: ./config/entrypoint.sh
    links:
      - db
    depends_on:
      - db