# Generated by Django 2.2.1 on 2019-05-28 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positon', models.CharField(choices=[('GOL', 'Goleiro'), ('LAT', 'Lateral'), ('ZAG', 'Zagueiro'), ('MEI', 'Meia'), ('ATA', 'Atacante'), ('TEC', 'Técnico')], max_length=50, verbose_name='Posição')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Posição',
                'verbose_name_plural': 'Posições',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DUV', 'Dúvida'), ('SUP', 'Suspenso'), ('PRO', 'Provável'), ('NUL', 'Nulo'), ('CON', 'Contutido')], default='NUL', max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('abbreviation', models.CharField(max_length=3, verbose_name='Abreviação')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Clube',
                'verbose_name_plural': 'Clubes',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Preço')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Position', verbose_name='Posição')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Team', verbose_name='Clube')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
            },
        ),
    ]
