# Generated by Django 2.2.1 on 2019-05-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GOL', 'Goleiro'), ('LAT', 'Lateral'), ('ZAG', 'Zagueiro'), ('MEI', 'Meia'), ('ATA', 'Atacante'), ('TEC', 'Técnico')], max_length=50, verbose_name='Posição'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
